# Generated by Django 3.1.3 on 2020-12-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20201203_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='detail',
            new_name='main_detail',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='second_detail',
            field=models.TextField(default='voici le test du detail 2'),
            preserve_default=False,
        ),
    ]
