# Generated by Django 3.1.3 on 2020-12-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20201203_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='main_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Main_detail'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='main_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Main_pic'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='second_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Second_detail'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='second_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Second_pic'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='Title'),
        ),
    ]
